Config templates
mmmh-studio/validator pull request #18
Opened 2020-02-14 15:08 UTC by Liamsi

To see the changes made to the config I've used for my test-sentry, have a look at this commit: https://github.com/mmmh-studio/validator/commit/81dd43bf61fba1df1f884f65c9641facbd0612c2

Note:
- templates can be supposedly be transformed into actual gaia config via: https://www.terraform.io/docs/configuration/functions/templatefile.html
- string templates according to: https://www.terraform.io/docs/configuration/expressions.html#string-templates

related reading: https://forum.cosmos.network/t/sentry-node-architecture-overview/454

2020-02-14 15:10 UTC, Liamsi commented on config-templates/sentry/config/config.toml
> +seeds = "&{sentry.seed_list}"
```suggestion
seeds = "${sentry.seed_list}"
```

2020-02-14 15:16 UTC, Liamsi commented
Following vars need to exist:

Sentry:
 - sentry.moniker
 - sentry.seed_list
 - sentry.validator_node_id
 - sentry.validator_node_ip
 - sentry.validator_node_port

validator:
 -validator.moniker
- validator.sentries

2020-02-19 15:14 UTC, Liamsi commented on config-templates/kms/tmkms.toml
> +addr = "${kms.validator_addr}"
This is particularly relevant.

2020-02-19 15:14 UTC, Liamsi commented on config-templates/kms/tmkms.toml
> +addr = "${kms.validator_addr}"
This is particularly relevant.

2020-02-20 11:28 UTC, xla requested changes
Dope!

Let's consolidate validator and sentry TOMLs and decide via the variables if it used as as either.

2020-02-20 11:28 UTC, xla commented on config-templates/validator/config/config.toml
> +laddr = "tcp://0.0.0.0:26656"
Let's explicitly configure NIC addresses for heighten securtiy.

2020-02-20 11:28 UTC, xla commented on config-templates/validator/config/config.toml
> +proxy_app = "tcp://127.0.0.1:26658"
Should be app name for `gaiad` use-case.

2020-02-20 11:28 UTC, xla commented on config-templates/validator/config/config.toml
> +db_dir = "data"
Should be configurable for flexibility with virtual storage.

2020-02-20 11:28 UTC, xla commented on config-templates/validator/config/config.toml
> +log_format = "plain"
Should be `json` for easier consumption in log infra.

2020-02-20 11:28 UTC, xla commented on config-templates/validator/config/config.toml
> +genesis_file = "config/genesis.json"
Config dir should be configurable and the path used here as var so we can store them and write them from the automation.

2020-02-20 11:28 UTC, xla commented on config-templates/validator/config/config.toml
> +priv_validator_key_file = "config/priv_validator_key.json"
Config dir.

2020-02-20 11:28 UTC, xla commented on config-templates/validator/config/config.toml
> +priv_validator_state_file = "data/priv_validator_state.json"
Data dir configurable.

2020-02-20 11:28 UTC, xla commented on config-templates/validator/config/config.toml
> +node_key_file = "config/node_key.json"
Config dir configurable.

2020-02-20 11:28 UTC, xla commented on config-templates/validator/config/config.toml
> +prof_laddr = "localhost:6060"
Is this metrics? Should also be configurable.

2020-02-20 11:28 UTC, xla commented on config-templates/validator/config/config.toml
> +laddr = "tcp://127.0.0.1:26657"
Let's turn off rpc.

2020-02-20 11:28 UTC, xla commented on config-templates/validator/config/config.toml
> +laddr = "tcp://127.0.0.1:26657"
Alternatively make it configurable so we can bind it to the utility network.

2020-02-24 11:01 UTC, Liamsi commented
All addressed in 
aab6170

2020-03-01 08:27 UTC, xla reviewed
Dope! Let's merge that bad boi.

📰 🍂 🌊 💻

2020-03-01 08:27 UTC, xla approved these changes

2020-03-13 11:50 UTC, merged

2020-03-13 11:50 UTC, Liamsi commented
Thanks @xla